# -*- coding: utf-8 -*-
_("Restart SoftCam")
_("Plugin Browser")
_("Extension Selection")
_("Sleeptimer")
_("Timer")
_("Channel zap +")
_("Channel zap -")
_("Channel zap (list) +")
_("Channel zap (list) -")
_("Dolby Digital downmix on/off")
_("List of Bouquets")
_("Channel list")
_("Zap history back")
_("Zap history next")
_("InfoBar")
_("InfoBar EventInfoPlugins")
_("InfoBar EventView")
_("InfoBar EPG")
_("InfoBar Multi EPG")
_("InfoBar Audio Selection")
_("InfoBar Show Radio")
_("InfoBar Show Tv")
_("InfoBar Show Movies")
_("InfoBar Record")
_("InfoBar Instant Record")
_("Start Timeshift")
_("Start Teletext")
_("Favourite channel 1")
_("Favourite channel 2")
_("Favourite channel 3")
_("Favourite channel 4")
_("Favourite channel 5")
_("Toggle AtmoLight")
_("Subservice Selection")
_("Subtitles")
_("MediaPlayer")
_("DVDPlayer")
_("Picture Player")
_("Cool TV Guide")
_("A/V Settings")
_("Switch 4:3 (Pillarbox) (Pan&Scan)")
_("Mount info")
_("Show PIP")
_("Swap PIP")
_("Move PIP")
_("Reboot")
_("GUI Restart")
_("DeepStandby")
